# Generated by Django 3.0.8 on 2020-07-16 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='kcal',
            new_name='kcal_per_100g',
        ),
    ]
