# Generated by Django 3.0.8 on 2020-08-13 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0002_auto_20200716_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealingredient',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_ingredients', to='meal.Meal'),
        ),
    ]
